server:
  port: ${APP_PORT:4545}
spring:
  application:
    name: ${APP_NAME:TASNIFLAGICH_SERVICE}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    username: postgres
    password: Shoxruh0912
    url: jdbc:postgresql://localhost:5432/xarid_mf_uz
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
springdoc:
  swagger-ui:
    path: /swagger-ui
    groups-order: asc
    operations-sorter: alpha
    try-it-out-enabled: true
    tags-sorter: alpha
    display-request-duration: true
  api-docs:
    path: /api/doc


api:
  info:
    title: Davlat Xaridlari Markaziy Axborot Portali
    description: Davlat Xaridlari Markaziy Axborot Portali proyektidagi API lar
    version: 1.2
    contact-name: Viktor Dimkov
    contact-email: theshd.0912@gmail.com
    contact-url: https://t.me/Cor_habe
    license-name: https://xarid.mf.uz
    license-url: https://xarid.mf.uz


