server:
  port: ${APP_PORT:7777}
spring:
  application:
    name: ${APP_NAME:ANOR_BANK_TASK}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    username: postgres
    password: Shoxruh0912
    url: jdbc:postgresql://localhost:5432/anor_bank
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true



