server:
  port: ${APP_PORT:7777}
spring:
  codec:
    max-in-memory-size: 16000KB
  application:
    name: ${APP_NAME:ANOR_BANK_TASK}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 20
    username: postgres
    password: 1234
    url: jdbc:postgresql://localhost:5432/dxmapdb
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update





